# Generated by Django 3.0.4 on 2020-12-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201127_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='تصویر'),
        ),
    ]
