# Generated by Django 3.0.4 on 2020-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201204_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(default='/img/default.jpg', null=True, upload_to='images', verbose_name='تصویر'),
        ),
    ]
