# Generated by Django 3.1.5 on 2021-01-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201218_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='مدرک دانشگاهی'),
        ),
    ]
