# Generated by Django 3.1.5 on 2021-01-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موقعیت شغلی'),
        ),
    ]
