# Generated by Django 4.1 on 2022-11-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledarticle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawledarticle',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='crawledarticle',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عنوان'),
        ),
    ]
