# Generated by Django 3.0.4 on 2020-10-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20201020_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
    ]
