# Generated by Django 4.0.2 on 2022-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('a', 'موجود'), ('u', 'ناموجود')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
