# Generated by Django 4.1 on 2022-10-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0008_alter_products_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
    ]
