# Generated by Django 4.1 on 2022-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0009_alter_imagemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
