# Generated by Django 4.1 on 2022-11-03 08:28

from django.db import migrations, models
import presentation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0010_imagemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('pre_text', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('post_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=presentation_app.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('a', 'موجود'), ('u', 'ناموجود')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
