# Generated by Django 4.1 on 2022-11-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0011_textmodel_alter_imagemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmodel',
            options={'verbose_name': 'متن', 'verbose_name_plural': 'متن ها'},
        ),
    ]
