# Generated by Django 4.1 on 2022-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0013_alter_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('a', 'موجود'), ('u', 'ناموجود')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
